# Page settings

baseurl = "https://resume.cameronboy.com/"
languageCode = "en-us"

theme = "orbit"
googleAnalytics = "UA-75773019-1"

# Do not build files for websites. Need them? Set to false
disableKinds=["404","RSS","sitemap"]

[params]

# Meta
    description = "Resume for Cameron Boy"
    author = "Cameron Boy"
    title = "Cameron Boy Resume"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Cameron Boy"
        tagline = "Unabashed Data Nerd"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: camerondavidboy@gmail.com"
        title = "email"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+19526078240"
        # title = "+19526078240"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://cameronboy.com"
        title = "cameronboy.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/cameronboy"
        title = "linkedin.com/in/cameronboy"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/cameronboy"
        title = "github.com/cameronboy"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/cboyrun"
        title = "@cboyrun"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Finance"
        college = "University of Minnesota"
        dates = "2009 - 2013"

        [[params.education.list]]
        degree = "BSc in MIS"
        college = "University of Minnesota"
        dates = "2009 - 2013"


    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "French"
        level = "Professional"

        [[params.language.list]]
        language = "Russian"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Coffee"

        [[params.interests.list]]
        interest = "Weightlifting"

        [[params.interests.list]]
        interest = "MotoGP"

        [[params.interests.list]]
        interest = "Machine Learning"

        [[params.interests.list]]
        interest = "Strong IPAs"



# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Data Analyst digging into the realm of data science through machine learning, python, and R.  Over the last couple of years I have been working as an analyst for a number of different organizations and developed a keen interest in machine learning & data science."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Finance Data Analyst"
        dates = "2017 - Present"
        company = "Johns Manville, Denver"
        details = "New analyst team within the finance department.\n - Working with Tableau to improve & automate a lot of finance deliverables\n - Go-to SQL person on the team - Working to introduce Python & R to the mix as well."

        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "2015 - 2017"
        company = "BIWorldwide, Minnesota"
        details = """With a team that provided multifaceted analytic support to multiple channels of a large, national-telecom client. We were on top of our descriptive analytics game and worked to apply a more systematic approach to analyses to extract deeper information from our data. I mined our hosted blog and ran sentiment analyses with R to shed light on open-eneded participant feedback. I also worked to utilize logistic regression to quantify the quality of referrals being made and provide groundwork for a hopeful future recommender system to offer the participant ways to improve the likelihood of their referral selling. And didsome cluster analyses on our program population to delve into promotion results and answer why some groups perform better than others. \n\nAlways explored other, external Developed models based on historical performance to predict incentive spend and facilitate fine tuning of sales incentive programs. Integrated R into some of our analyses for both internal & external stakeholders. Final reporting is rendered in HTML with the knitr & flexdashboard packages allowing for great deal of interactivity between the stakeholder and the data for those without Tableau licenses."""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Tableau"
        level = "95%"

        [[params.skills.list]]
        skill = "Python"
        level = "50%"

        [[params.skills.list]]
        skill = "R"
        level = "50%"

        [[params.skills.list]]
        skill = "Tidyverse - R"
        level = "45%"

        [[params.skills.list]]
        skill = "Pandas - Python"
        level = "45%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Cameron Boy"
