# Page settings

baseurl = "https://resume.cameronboy.com/"
languageCode = "en-us"

theme = "orbit"
googleAnalytics = "UA-114358546-1"

# Do not build files for websites. Need them? Set to false
disableKinds=["404","RSS","sitemap"]

[params]

# Meta
    description = "Resume for Cameron Boy"
    author = "Cameron Boy"
    title = "Cameron Boy Info"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Cameron Boy"
        tagline = "Data Nerd; Python, R enthusiast"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: camerondavidboy@gmail.com"
        title = "email"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+19526078240"
        # title = "+19526078240"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://cameronboy.com"
        title = "cameronboy.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/cameronboy"
        title = "linkedin.cameronboy.com"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/cameronboy"
        title = "github.com/cameronboy"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/cboyrun"
        title = "@cboyrun"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Finance"
        college = "University of Minnesota"
        dates = "2009 - 2013"

        [[params.education.list]]
        degree = "BSc in MIS"
        college = "University of Minnesota"
        dates = "2009 - 2013"

        [[params.education.list]]
        degree = "Udacity"

        [[params.education.list]]
        degree = "Coursera"

        [[params.education.list]]
        degree = "DataCamp"
        
        



    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "French"
        level = "Professional"

        [[params.language.list]]
        language = "Russian"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Coffee"

        [[params.interests.list]]
        interest = "Weightlifting"

        [[params.interests.list]]
        interest = "MotoGP"

        [[params.interests.list]]
        interest = "Machine Learning"

        [[params.interests.list]]
        interest = "Strong IPAs"



# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "<strong>An experienced Data Analyst always looking to learn new and creative ways operate.</strong> The last couple years have seen a transition to learning python, R and working through some moocs. <li>[Andrew Ng's machine learning course](https://www.coursera.org/learn/machine-learning)</li> <li>[Udacity's Deep Learning Nanodegree](https://www.udacity.com/course/deep-learning-nanodegree--nd101)</li><li>[Intro & Intermediate R & Python for Data Science](https://datacamp.com)</li>"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experience"

        [[params.jobs.list]]
        position = "Decision Scientist"
        dates = "Dec 2018 - Present"
        company = "Ibotta, Inc"
        details = """<strong>Our team is the analytical and technical support for our client success teams. Our work aims to provide automated, multifaceted campaign results via a multitude of tools include SQL, Spark, Python, and Apache Airflow.</strong>
        <li>Compiled campaign meta data via python in varying structures from S3, old Excel files local & Google Drive, and an internal API into one structured data set.</li>
        <li>Ran k-means clustering algorithm to provide a client with a two mathematically alike cities for a test/control breakout.</li>
        <li>Addressing continual support requests with adding functionality to our internal python module for rest of the team to use.</li>
        <li>Provide adhoc support as required from our client success teams.</li>
        <li>...more to come.</li>"""


        [[params.jobs.list]]
        position = "Finance Data Analyst"
        dates = "Aug 2017 - Dec 2018"
        company = "Johns Manville"
        details = '<strong>I worked to provide a technical background to our data projects with SQL support, advanced tableau, and python on our team within the finance department.</strong> Our team operates in close contact with the CFO to be the central analytics hub and to provide advanced data & analytics support to Johns Manville finance.<li>Introduced python to our team with ETL pipelines to feed our MSSQL database.</li><li>Built a model with keras (tensorflow backend) in python to estimate tax liabilities to bring potential errors to the attention of our tax department thus reducing the possibility of incurring consultant fees.</li><li>Managed analytics projects to completion supporting commercial sales analytics to internal tax reconciliation</li>'

        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "Mar 2015 - Aug 2017"
        company = "BIWorldwide"
        details = 'With a team that provided multifaceted analytic support for multiple channels of a large, national-telecom client. We were on top of our descriptive analytics game and worked to apply a more systematic approach to analysis to extract deeper information from our data.<li>I mined our hosted blog and ran sentiment analyses with R to shed light on open-eneded participant feedback.</li><li>Developed a logistic regression model to determine the probability of referrals selling, and experimented with clustering on our program population to delve into promotion results and answer why some groups perform better than others.</li><li>Integrated R into some of our analyses for both internal and external stakeholder with final reporting is rendered in HTML with the knitr and flexdashboard packages allowing for great deal of interactivity between the stakeholder and the data for those without Tableau licenses.</li>'


        [[params.jobs.list]]
        position = "Project Coordinator"
        dates = "Sep 2014 - Mar 2015"
        company = "BIWorldwide"
        details = 'Our team ran and operated the incentive programs for numerous automobile clients through an in-house developed web app, back-end databases and procedures, reporting, and client support.<li>Learned SQL on the job moved all of our excel reporting to SQL saving our monday mornings.</li><li>Support Business Analysts with fielding of participant inquiries in a timely manner.</li><li>Responsible for development and execution of day-to-day sales reporting distributed to the client.</li><li>Complete documentation of database and Website procedures.</li>'


        [[params.jobs.list]]
        position = "Data Analyst"
        dates = "Jun 2013 - Sep 2014"
        company = "AmerisourceBergen"
        details = '<li>Designed, developed, implemented, and tested new processes and dashboards that improved data analysis and tracking, reduced cost, and improved process effectiveness and accuracy.</li><li>Directly oversaw 10+ of these analysis processes that monitor our performance on compliance contracts valued at millions in quarterly revenue.</li><li>Consulted with end-users on their requirements to drive my report design, development and testing.</li><li>Communicated with our pharmaceutical buyers on actionable steps towards maximizing our inventory position whilst minimizing penalties associated with erratic purchasing activity.</li><li>Conducted mathematical analysis of inventory/service level data to ensure maximum reward payment from our contracted suppliers.</li>'



    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "<strong>Some of the side projects I am working on in my spare time</strong>"

        [[params.projects.list]]
        title = "Site Response Monitoring"
        url = "https://github.com/cameronboy/site_response_monitoring"
        tagline = "A python script to test bandwidth to popular content providers and log to Google sheets."
        
        [[params.projects.list]]
        title = "Neural Network in pure numpy - Udacity project"
        url = "https://github.com/cameronboy/DLND-P1/blob/master/Neural%20Network%20-%20Bike%20Demand%20Prediction.ipynb"
        tagline = "A vanilla neural network implemented in pure `numpy` to predict bike sharing demand."
        
        [[params.projects.list]]
        title = 'NLP - Machine Translation - Udacity project'
        url = "https://github.com/cameronboy/DLND-P4/blob/master/dlnd_language_translation.ipynb"
        tagline = 'A sequence to sequence model translating english text to french.'
        
        [[params.projects.list]]
        title = "Sudoku solver - Udacity project"
        url = "https://github.com/cameronboy/aind-sudoku"
        tagline = "An intelligent agent that solves sudoku puzzles."

        [[params.projects.list]]
        title = 'Isolation Agent - Udacity project'
        url = 'https://github.com/cameronboy/aind-isolation'
        tagline = 'An agent utilizing alpha-beta pruning to play isolation.'

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Tableau"
        level = "95%"

        [[params.skills.list]]
        skill = "Python"
        level = "75%"

        [[params.skills.list]]
        skill = "R"
        level = "75%"

        [[params.skills.list]]
        skill = "Pandas - Python"
        level = "70%"

        [[params.skills.list]]
        skill = "Tidyverse - R"
        level = "70%"



    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Cameron Boy"
